# Generated by Django 3.2.4 on 2021-06-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=60, null=True)),
                ('quote_no', models.CharField(blank=True, max_length=60, null=True)),
                ('insurance_type', models.CharField(blank=True, max_length=60, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=60, null=True)),
                ('date_form', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotations2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=60, null=True)),
                ('quote', models.CharField(blank=True, max_length=60, null=True)),
                ('client_name', models.CharField(blank=True, max_length=60, null=True)),
                ('insurance_type', models.CharField(blank=True, max_length=60, null=True)),
                ('cover_period', models.CharField(blank=True, max_length=60, null=True)),
                ('insurance_name', models.CharField(blank=True, max_length=60, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quot2', to='app.quotations2')),
            ],
        ),
    ]
