# Generated by Django 3.2.4 on 2021-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_form',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date_to',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
