# Generated by Django 3.2.4 on 2021-06-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210623_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=60, null=True)),
                ('insurer', models.CharField(blank=True, max_length=30, null=True)),
                ('currency', models.CharField(blank=True, max_length=30, null=True)),
                ('xrate', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('days', models.CharField(blank=True, max_length=60, null=True)),
                ('file_no', models.CharField(blank=True, max_length=50, null=True)),
                ('first_loss_payee', models.CharField(blank=True, max_length=40, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('businee', models.CharField(blank=True, max_length=40, null=True)),
                ('businee_type', models.CharField(blank=True, max_length=40, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=10, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=40, null=True)),
                ('insured_name', models.CharField(blank=True, max_length=30, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=30, null=True)),
                ('windscreen_sum_insured', models.CharField(blank=True, max_length=40, null=True)),
                ('sum_insured', models.CharField(blank=True, max_length=60, null=True)),
                ('autual_premium', models.CharField(blank=True, max_length=30, null=True)),
                ('cover', models.CharField(blank=True, max_length=60, null=True)),
                ('insurance', models.CharField(blank=True, max_length=10, null=True)),
                ('chassis', models.CharField(blank=True, max_length=10, null=True)),
                ('manufacture_Year', models.CharField(blank=True, max_length=40, null=True)),
                ('windscreen_premium', models.CharField(blank=True, max_length=30, null=True)),
                ('rate', models.CharField(blank=True, max_length=12, null=True)),
                ('adjust', models.CharField(blank=True, max_length=30, null=True)),
                ('sticker', models.CharField(blank=True, max_length=30, null=True)),
                ('insurance_class', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_year', models.CharField(blank=True, max_length=20, null=True)),
                ('Accessories_sum_insured', models.CharField(blank=True, max_length=10, null=True)),
                ('Override', models.CharField(blank=True, max_length=60, null=True)),
                ('total_premium', models.CharField(blank=True, max_length=600, null=True)),
                ('period_of_insurance', models.CharField(blank=True, max_length=300, null=True)),
                ('other_description', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=400, null=True)),
                ('seat', models.CharField(blank=True, max_length=500, null=True)),
                ('accessories_information', models.CharField(blank=True, max_length=100, null=True)),
                ('tppd_free_limit', models.CharField(blank=True, max_length=80, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=70, null=True)),
                ('cc', models.CharField(blank=True, max_length=30, null=True)),
                ('tppd_increase_limit', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_category', models.CharField(blank=True, max_length=200, null=True)),
                ('model_no', models.CharField(blank=True, max_length=300, null=True)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=40, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=40, null=True)),
                ('tare_weight', models.CharField(blank=True, max_length=40, null=True)),
                ('number_of_axel', models.CharField(blank=True, max_length=40, null=True)),
                ('axel_distance', models.CharField(blank=True, max_length=40, null=True)),
                ('short_period', models.CharField(blank=True, max_length=30, null=True)),
                ('motar_category', models.CharField(blank=True, max_length=30, null=True)),
                ('motar_usage', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
