from django.db import models

class Quotation(models.Model):
    client_name = models.CharField(max_length=60,null=True,blank=True)
    quote_no = models.CharField(max_length=60,null=True,blank=True)
    insurance_type = models.CharField(max_length=60,null=True,blank=True)
    registration_no = models.CharField(max_length=60,null=True,blank=True)
    date_form = models.CharField(max_length=10,null=True,blank=True)
    date_to = models.CharField(max_length=10,null=True,blank=True)
    status = models.CharField(max_length=60,null=True,blank=True)
    def __str__(self):
        return self.client_name
class Quotations2(models.Model):
    branch = models.CharField(max_length=60,null=True,blank=True)
    quote = models.CharField(max_length=60,null=True,blank=True)
    client_name = models.CharField(max_length=60,null=True,blank=True)   
    insurance_type = models.CharField(max_length=60,null=True,blank=True)
    cover_period = models.CharField(max_length=60,null=True,blank=True)
    insurance_name = models.CharField(max_length=60,null=True,blank=True)
    amount = models.IntegerField(null=True,blank=True)
    status = models.CharField(max_length=60,null=True,blank=True)
    def __str__(self):
        return self.branch
# class Update(models.Model):
#     quot2 = models.ForeignKey(Quotations2,on_delete=models.CASCADE,related_name='quot2')
#     def __str__(self):
#         return str(self.quot2)
class Vehicle(models.Model):
    client_name = models.CharField(max_length=60,null=True,blank=True)
    insurer = models.CharField(max_length=30,null=True,blank=True)
    currency = models.CharField(max_length=30,null=True,blank=True)
    rate = models.CharField(max_length=30,null=True,blank=True)
    xrate = models.CharField(max_length=60,null=True,blank=True)
    address = models.TextField(null=True,blank=True)
    date_from = models.DateField()
    date_to = models.DateField()
    days = models.CharField(max_length=60,null=True,blank=True)
    file_no = models.CharField(max_length=50,null=True,blank=True)
    first_loss_payee = models.CharField(max_length=40,null=True,blank=True)
    branch = models.CharField(max_length=50,null=True,blank=True)
    businee = models.CharField(max_length=40,null=True,blank=True)
    businee_type = models.CharField(max_length=40,null=True,blank=True)
    registration_no = models.CharField(max_length=10,null=True,blank=True)
    chassis_no = models.CharField(max_length=40,null=True,blank=True)
    insured_name = models.CharField(max_length=30,null=True,blank=True)
    # registration_no = models.CharField(max_length=20,null=True,blank=True)
    fuel_type = models.CharField(max_length=30,null=True,blank=True)
    windscreen_sum_insured = models.CharField(max_length=40,null=True,blank=True)
    sum_insured = models.CharField(max_length=60,null=True,blank=True)
    autual_premium = models.CharField(max_length=30,null=True,blank=True)
    cover = models.CharField(max_length=60,null=True,blank=True)
    insurance = models.CharField(max_length=10,null=True,blank=True)
    chassis = models.CharField(max_length=10,null=True,blank=True)
    manufacture_Year =models.CharField(max_length=40,null=True,blank=True)
    windscreen_premium = models.CharField(max_length=30,null=True,blank=True)
    rate = models.CharField(max_length=12,null=True,blank=True)
    adjust = models.CharField(max_length=30,null=True,blank=True)
    sticker = models.CharField(max_length=30,null=True,blank=True)
    insurance_class = models.CharField(max_length=30,null=True,blank=True)
    vehicle_make = models.CharField(max_length=30,null=True,blank=True)
    registration_year = models.CharField(max_length=20,null=True,blank=True)
    Accessories_sum_insured = models.CharField(max_length=10,null=True,blank=True)
    Override = models.CharField(max_length=60,null=True,blank=True)
    total_premium = models.CharField(max_length=600,null=True,blank=True)
    period_of_insurance = models.CharField(max_length=300,null=True,blank=True)
    other_description = models.CharField(max_length=300,null=True,blank=True)
    vehicle_model = models.CharField(max_length=400,null=True,blank=True)
    seat = models.CharField(max_length=500,null=True,blank=True)
    accessories_information = models.CharField(max_length=100,null=True,blank=True)
    tppd_free_limit = models.CharField(max_length=80,null=True,blank=True)
    vehicle_type = models.CharField(max_length=70,null=True,blank=True)
    cc = models.CharField(max_length=30,null=True,blank=True)
    tppd_increase_limit = models.CharField(max_length=20,null=True,blank=True)
    owner_category = models.CharField(max_length=200,null=True,blank=True)
    model_no = models.CharField(max_length=300,null=True,blank=True)
    motar_category = models.CharField(max_length=200,null=True,blank=True)
    color = models.CharField(max_length=40,null=True,blank=True)
    engine_no = models.CharField(max_length=40,null=True,blank=True)
    gross_weight = models.CharField(max_length=40,null=True,blank=True)
    tare_weight = models.CharField(max_length=40,null=True,blank=True)
    number_of_axel = models.CharField(max_length=40,null=True,blank=True)
    axel_distance = models.CharField(max_length=40,null=True,blank=True)
    short_period = models.CharField(max_length=30,null=True,blank=True)
    motar_category = models.CharField(max_length=30,null=True,blank=True)
    motar_usage = models.CharField(max_length=30,null=True,blank=True)
    def __str__(self):
        return self.client_name